## https://www.mongodb.com/ko-kr/docs/atlas/cli/current/atlas-cli-deploy-docker/
services:
  mongodb_service:
    image: mongodb/mongodb-atlas-local:latest
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./data:/data/db
      - ./config:/data/configdb
