version: "3"
services:
  mariadb_service:
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul