

name: cluster
services:
  ## redis-cluster-initializer는 redis-cli 명령어를 수행하여 클러스터 노드를 지정하고 초기화 
  redis-cluster-initializer:
    image: redis:7.2.4-alpine
    container_name: redis-cluster-initializer
    command: redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 --cluster-replicas 1
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
  redis-node-1:
    image: redis:7.2.4-alpine
    container_name: redis-node-1
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  redis-node-2:
    image: redis:7.2.4-alpine
    container_name: redis-node-2
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  redis-node-3:
    image: redis:7.2.4-alpine
    container_name: redis-node-3
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  redis-node-4:
    image: redis:7.2.4-alpine
    container_name: redis-node-4
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  redis-node-5:
    image: redis:7.2.4-alpine
    container_name: redis-node-5
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  redis-node-6:
    image: redis:7.2.4-alpine
    container_name: redis-node-6
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  